version: '3'
services:

  #Back End API
  face-recognition-api:
    container_name: backend
    # image: node:12.3.2
    build: ./
    command: npm start
    working_dir: /usr/src/face-recognition
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/face-recognition-docker
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB: face-recognition-docker
      # POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/face-recognition

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: face-recognition-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
