version: '3'
services:
  face-recognition-api:
    container_name: backend
    # image: node:12.3.2
    build: ./
    command: npm start
    working_dir: /usr/src/face-recognition
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/face-recognition
